// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/muhwyndhamhp/tigerhall-kittens/graph/model"
)

// TigerUsecase is an autogenerated mock type for the TigerUsecase type
type TigerUsecase struct {
	mock.Mock
}

// CreateTiger provides a mock function with given fields: ctx, tiger, userID
func (_m *TigerUsecase) CreateTiger(ctx context.Context, tiger *model.NewTiger, userID uint) (*model.Tiger, error) {
	ret := _m.Called(ctx, tiger, userID)

	var r0 *model.Tiger
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.NewTiger, uint) (*model.Tiger, error)); ok {
		return rf(ctx, tiger, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.NewTiger, uint) *model.Tiger); ok {
		r0 = rf(ctx, tiger, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Tiger)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.NewTiger, uint) error); ok {
		r1 = rf(ctx, tiger, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTigerByID provides a mock function with given fields: ctx, id
func (_m *TigerUsecase) GetTigerByID(ctx context.Context, id uint) (*model.Tiger, error) {
	ret := _m.Called(ctx, id)

	var r0 *model.Tiger
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*model.Tiger, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *model.Tiger); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Tiger)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTigers provides a mock function with given fields: ctx, page, pageSize
func (_m *TigerUsecase) GetTigers(ctx context.Context, page int, pageSize int) ([]*model.Tiger, int, error) {
	ret := _m.Called(ctx, page, pageSize)

	var r0 []*model.Tiger
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*model.Tiger, int, error)); ok {
		return rf(ctx, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*model.Tiger); ok {
		r0 = rf(ctx, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Tiger)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = rf(ctx, page, pageSize)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewTigerUsecase creates a new instance of TigerUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTigerUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *TigerUsecase {
	mock := &TigerUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
